INSERT INTO `manus` (id, name) VALUES ('1','Aprilia')
INSERT INTO `manus` (id, name) VALUES ('42','Aston Martin')
INSERT INTO `manus` (id, name) VALUES ('43','Audi')
INSERT INTO `manus` (id, name) VALUES ('2','Avon')
INSERT INTO `manus` (id, name) VALUES ('3','Bajaj')
INSERT INTO `manus` (id, name) VALUES ('4','Benelli')
INSERT INTO `manus` (id, name) VALUES ('45','Bentley')
INSERT INTO `manus` (id, name) VALUES ('5','BMW')
INSERT INTO `manus` (id, name) VALUES ('47','Bugatti')
INSERT INTO `manus` (id, name) VALUES ('39','Chevrolet')
INSERT INTO `manus` (id, name) VALUES ('48','Datsun')
INSERT INTO `manus` (id, name) VALUES ('49','DC')
INSERT INTO `manus` (id, name) VALUES ('6','Ducati')
INSERT INTO `manus` (id, name) VALUES ('50','Ferrari')
INSERT INTO `manus` (id, name) VALUES ('51','Fiat')
INSERT INTO `manus` (id, name) VALUES ('52','Force')
INSERT INTO `manus` (id, name) VALUES ('38','Ford')
INSERT INTO `manus` (id, name) VALUES ('7','Harley Davidson')
INSERT INTO `manus` (id, name) VALUES ('8','Hero')
INSERT INTO `manus` (id, name) VALUES ('9','HeroElectric')
INSERT INTO `manus` (id, name) VALUES ('10','Honda')
INSERT INTO `manus` (id, name) VALUES ('11','Hyosung')
INSERT INTO `manus` (id, name) VALUES ('33','Hyundai')
INSERT INTO `manus` (id, name) VALUES ('53','ICML')
INSERT INTO `manus` (id, name) VALUES ('12','Indian Motorcycle')
INSERT INTO `manus` (id, name) VALUES ('13','Indus')
INSERT INTO `manus` (id, name) VALUES ('54','Isuzu')
INSERT INTO `manus` (id, name) VALUES ('55','Jaguar')
INSERT INTO `manus` (id, name) VALUES ('56','Jeep')
INSERT INTO `manus` (id, name) VALUES ('14','Kawasaki')
INSERT INTO `manus` (id, name) VALUES ('15','KTM')
INSERT INTO `manus` (id, name) VALUES ('57','Lamborghini')
INSERT INTO `manus` (id, name) VALUES ('58','Land Rover')
INSERT INTO `manus` (id, name) VALUES ('16','Lectrix')
INSERT INTO `manus` (id, name) VALUES ('17','LML')
INSERT INTO `manus` (id, name) VALUES ('18','Lohia')
INSERT INTO `manus` (id, name) VALUES ('19','Mahindra')
INSERT INTO `manus` (id, name) VALUES ('59','Mahindra SsangYong')
INSERT INTO `manus` (id, name) VALUES ('32','Maruti Suzuki')
INSERT INTO `manus` (id, name) VALUES ('60','Maserati')
INSERT INTO `manus` (id, name) VALUES ('61','Mercedes-Benz')
INSERT INTO `manus` (id, name) VALUES ('62','Mini')
INSERT INTO `manus` (id, name) VALUES ('63','Mitsubishi')
INSERT INTO `manus` (id, name) VALUES ('20','Moto Guzzi')
INSERT INTO `manus` (id, name) VALUES ('21','MV Agusta')
INSERT INTO `manus` (id, name) VALUES ('64','Nissan')
INSERT INTO `manus` (id, name) VALUES ('22','Polaris')
INSERT INTO `manus` (id, name) VALUES ('65','Porsche')
INSERT INTO `manus` (id, name) VALUES ('66','Premier')
INSERT INTO `manus` (id, name) VALUES ('23','Regal Raptor')
INSERT INTO `manus` (id, name) VALUES ('40','Renault')
INSERT INTO `manus` (id, name) VALUES ('67','Rolls-Royce')
INSERT INTO `manus` (id, name) VALUES ('24','Royal Enfield')
INSERT INTO `manus` (id, name) VALUES ('68','Skoda')
INSERT INTO `manus` (id, name) VALUES ('25','Suzuki')
INSERT INTO `manus` (id, name) VALUES ('37','Tata')
INSERT INTO `manus` (id, name) VALUES ('26','Terra Motors')
INSERT INTO `manus` (id, name) VALUES ('35','Toyota')
INSERT INTO `manus` (id, name) VALUES ('27','Triumph')
INSERT INTO `manus` (id, name) VALUES ('28','TVS')
INSERT INTO `manus` (id, name) VALUES ('29','Vespa')
INSERT INTO `manus` (id, name) VALUES ('30','Vibgyor')
INSERT INTO `manus` (id, name) VALUES ('41','Volkswagen')
INSERT INTO `manus` (id, name) VALUES ('69','Volvo')
INSERT INTO `manus` (id, name) VALUES ('31','Yamaha')


INSERT INTO `models` (id, manu_id, name) VALUES ('1','1','Caponord')
 INSERT INTO `models` (id, manu_id, name) VALUES ('2','1','Dorsoduro')
 INSERT INTO `models` (id, manu_id, name) VALUES ('3','1','Mana')
 INSERT INTO `models` (id, manu_id, name) VALUES ('4','1','RSV4')
 INSERT INTO `models` (id, manu_id, name) VALUES ('5','1','SRV 850')
 INSERT INTO `models` (id, manu_id, name) VALUES ('6','1','Tuono V4 R')
 INSERT INTO `models` (id, manu_id, name) VALUES ('7','2','E-Bike')
 INSERT INTO `models` (id, manu_id, name) VALUES ('8','2','E-Bike VX')
 INSERT INTO `models` (id, manu_id, name) VALUES ('9','2','E-Lite')
 INSERT INTO `models` (id, manu_id, name) VALUES ('10','2','E-Mate')
 INSERT INTO `models` (id, manu_id, name) VALUES ('11','2','E-Plus')
 INSERT INTO `models` (id, manu_id, name) VALUES ('12','2','E-Scoot')
 INSERT INTO `models` (id, manu_id, name) VALUES ('13','2','E-Star')
 INSERT INTO `models` (id, manu_id, name) VALUES ('14','3','Avenger')
 INSERT INTO `models` (id, manu_id, name) VALUES ('15','3','CT 100')
 INSERT INTO `models` (id, manu_id, name) VALUES ('16','3','Discover')
 INSERT INTO `models` (id, manu_id, name) VALUES ('17','3','Platina')
 INSERT INTO `models` (id, manu_id, name) VALUES ('18','3','Pulsar')
 INSERT INTO `models` (id, manu_id, name) VALUES ('19','4','TNT ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('20','4','Tornado')
 INSERT INTO `models` (id, manu_id, name) VALUES ('21','4','Tre K')
 INSERT INTO `models` (id, manu_id, name) VALUES ('372','5','1 Series')
 INSERT INTO `models` (id, manu_id, name) VALUES ('373','5','3-Series')
 INSERT INTO `models` (id, manu_id, name) VALUES ('374','5','5-Series')
 INSERT INTO `models` (id, manu_id, name) VALUES ('375','5','6-Series')
 INSERT INTO `models` (id, manu_id, name) VALUES ('376','5','7-Series')
 INSERT INTO `models` (id, manu_id, name) VALUES ('377','5','i8')
 INSERT INTO `models` (id, manu_id, name) VALUES ('22','5','K')
 INSERT INTO `models` (id, manu_id, name) VALUES ('378','5','M3')
 INSERT INTO `models` (id, manu_id, name) VALUES ('379','5','M4')
 INSERT INTO `models` (id, manu_id, name) VALUES ('380','5','M5')
 INSERT INTO `models` (id, manu_id, name) VALUES ('381','5','M6 Gran Coupe')
 INSERT INTO `models` (id, manu_id, name) VALUES ('23','5','R')
 INSERT INTO `models` (id, manu_id, name) VALUES ('24','5','S')
 INSERT INTO `models` (id, manu_id, name) VALUES ('382','5','X1')
 INSERT INTO `models` (id, manu_id, name) VALUES ('383','5','X3')
 INSERT INTO `models` (id, manu_id, name) VALUES ('387','5','X4')
 INSERT INTO `models` (id, manu_id, name) VALUES ('384','5','X5')
 INSERT INTO `models` (id, manu_id, name) VALUES ('385','5','X6')
 INSERT INTO `models` (id, manu_id, name) VALUES ('386','5','Z4')
 INSERT INTO `models` (id, manu_id, name) VALUES ('26','6','Diavel')
 INSERT INTO `models` (id, manu_id, name) VALUES ('27','6','Hypermotard')
 INSERT INTO `models` (id, manu_id, name) VALUES ('28','6','Hyperstrada')
 INSERT INTO `models` (id, manu_id, name) VALUES ('29','6','Monster ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('30','6','Multistrada')
 INSERT INTO `models` (id, manu_id, name) VALUES ('25','6','Panigale')
 INSERT INTO `models` (id, manu_id, name) VALUES ('31','6','Scrambler')
 INSERT INTO `models` (id, manu_id, name) VALUES ('32','6','Scrambler Sixty2')
 INSERT INTO `models` (id, manu_id, name) VALUES ('33','6','XDiavel')
 INSERT INTO `models` (id, manu_id, name) VALUES ('34','7','Breakout')
 INSERT INTO `models` (id, manu_id, name) VALUES ('35','7','CVO Limited')
 INSERT INTO `models` (id, manu_id, name) VALUES ('36','7','Fat Bob')
 INSERT INTO `models` (id, manu_id, name) VALUES ('37','7','Fat Boy')
 INSERT INTO `models` (id, manu_id, name) VALUES ('38','7','Forty Eight')
 INSERT INTO `models` (id, manu_id, name) VALUES ('46','7','Freewheeler')
 INSERT INTO `models` (id, manu_id, name) VALUES ('39','7','Heritage Softail Classic')
 INSERT INTO `models` (id, manu_id, name) VALUES ('40','7','Iron 883')
 INSERT INTO `models` (id, manu_id, name) VALUES ('41','7','Night Rod Special')
 INSERT INTO `models` (id, manu_id, name) VALUES ('42','7','Street 750')
 INSERT INTO `models` (id, manu_id, name) VALUES ('43','7','Street Bob')
 INSERT INTO `models` (id, manu_id, name) VALUES ('44','7','Street Glide Special')
 INSERT INTO `models` (id, manu_id, name) VALUES ('45','7','Super Low')
 INSERT INTO `models` (id, manu_id, name) VALUES ('75','8','Dare')
 INSERT INTO `models` (id, manu_id, name) VALUES ('76','8','Dash')
 INSERT INTO `models` (id, manu_id, name) VALUES ('47','8','Duet')
 INSERT INTO `models` (id, manu_id, name) VALUES ('48','8','Glamour')
 INSERT INTO `models` (id, manu_id, name) VALUES ('77','8','Hastur')
 INSERT INTO `models` (id, manu_id, name) VALUES ('49','8','HF Dawn')
 INSERT INTO `models` (id, manu_id, name) VALUES ('50','8','HF Deluxe')
 INSERT INTO `models` (id, manu_id, name) VALUES ('51','8','Hunk')
 INSERT INTO `models` (id, manu_id, name) VALUES ('78','8','HX 250R')
 INSERT INTO `models` (id, manu_id, name) VALUES ('52','8','Ignitor')
 INSERT INTO `models` (id, manu_id, name) VALUES ('53','8','Karizma')
 INSERT INTO `models` (id, manu_id, name) VALUES ('79','8','Leap')
 INSERT INTO `models` (id, manu_id, name) VALUES ('54','8','Maestro')
 INSERT INTO `models` (id, manu_id, name) VALUES ('55','8','Passion')
 INSERT INTO `models` (id, manu_id, name) VALUES ('56','8','Passion Pro')
 INSERT INTO `models` (id, manu_id, name) VALUES ('57','8','Pleasure')
 INSERT INTO `models` (id, manu_id, name) VALUES ('80','8','RNT')
 INSERT INTO `models` (id, manu_id, name) VALUES ('58','8','Splendor')
 INSERT INTO `models` (id, manu_id, name) VALUES ('59','8','Splendor Pro Classic')
 INSERT INTO `models` (id, manu_id, name) VALUES ('73','8','Xtreme')
 INSERT INTO `models` (id, manu_id, name) VALUES ('74','8','Xtreme Sports')
 INSERT INTO `models` (id, manu_id, name) VALUES ('81','8','ZIR')
 INSERT INTO `models` (id, manu_id, name) VALUES ('82','9','Avior')
 INSERT INTO `models` (id, manu_id, name) VALUES ('83','9','Cruz')
 INSERT INTO `models` (id, manu_id, name) VALUES ('84','9','E-Sprint')
 INSERT INTO `models` (id, manu_id, name) VALUES ('85','9','Maxi')
 INSERT INTO `models` (id, manu_id, name) VALUES ('86','9','Optima Plus')
 INSERT INTO `models` (id, manu_id, name) VALUES ('87','9','Photon')
 INSERT INTO `models` (id, manu_id, name) VALUES ('88','9','Wave DX')
 INSERT INTO `models` (id, manu_id, name) VALUES ('89','9','Zion')
 INSERT INTO `models` (id, manu_id, name) VALUES ('257','10','Accord')
 INSERT INTO `models` (id, manu_id, name) VALUES ('90','10','Activa')
 INSERT INTO `models` (id, manu_id, name) VALUES ('489','10','Eterno')
 INSERT INTO `models` (id, manu_id, name) VALUES ('251','10','Amaze')
 INSERT INTO `models` (id, manu_id, name) VALUES ('91','10','Aviator')
 INSERT INTO `models` (id, manu_id, name) VALUES ('258','10','BR-V')
 INSERT INTO `models` (id, manu_id, name) VALUES ('252','10','Brio')
 INSERT INTO `models` (id, manu_id, name) VALUES ('259','10','Brio SUV')
 INSERT INTO `models` (id, manu_id, name) VALUES ('92','10','CB 1000R')
 INSERT INTO `models` (id, manu_id, name) VALUES ('93','10','CB Shine')
 INSERT INTO `models` (id, manu_id, name) VALUES ('94','10','CB Trigger')
 INSERT INTO `models` (id, manu_id, name) VALUES ('95','10','CB Unicorn 160')
 INSERT INTO `models` (id, manu_id, name) VALUES ('96','10','CBR ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('97','10','CD 110 Dream')
 INSERT INTO `models` (id, manu_id, name) VALUES ('253','10','City')
 INSERT INTO `models` (id, manu_id, name) VALUES ('254','10','CR-V')
 INSERT INTO `models` (id, manu_id, name) VALUES ('98','10','Dio 2015')
 INSERT INTO `models` (id, manu_id, name) VALUES ('99','10','Dream Neo 2015')
 INSERT INTO `models` (id, manu_id, name) VALUES ('100','10','Dream Yuga 2015')
 INSERT INTO `models` (id, manu_id, name) VALUES ('101','10','Gold Wing')
 INSERT INTO `models` (id, manu_id, name) VALUES ('102','10','Hornet 160R')
 INSERT INTO `models` (id, manu_id, name) VALUES ('256','10','Jazz')
 INSERT INTO `models` (id, manu_id, name) VALUES ('106','10','Lead')
 INSERT INTO `models` (id, manu_id, name) VALUES ('103','10','Livo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('255','10','Mobilio MPV')
 INSERT INTO `models` (id, manu_id, name) VALUES ('107','10','NXR 160')
 INSERT INTO `models` (id, manu_id, name) VALUES ('108','10','PCX')
 INSERT INTO `models` (id, manu_id, name) VALUES ('260','10','Vezel')
 INSERT INTO `models` (id, manu_id, name) VALUES ('104','10','VFR 1200 F')
 INSERT INTO `models` (id, manu_id, name) VALUES ('105','10','VT 1300 CX')
 INSERT INTO `models` (id, manu_id, name) VALUES ('109','11','Aquila')
 INSERT INTO `models` (id, manu_id, name) VALUES ('112','11','GD')
 INSERT INTO `models` (id, manu_id, name) VALUES ('110','11','GT')
 INSERT INTO `models` (id, manu_id, name) VALUES ('111','11','ST7')
 INSERT INTO `models` (id, manu_id, name) VALUES ('113','12','Chief Dark Horse')
 INSERT INTO `models` (id, manu_id, name) VALUES ('114','12','Indian Chief Classic')
 INSERT INTO `models` (id, manu_id, name) VALUES ('115','12','Indian Chief Vintage')
 INSERT INTO `models` (id, manu_id, name) VALUES ('116','12','Indian Chieftain')
 INSERT INTO `models` (id, manu_id, name) VALUES ('117','12','Roadmaster')
 INSERT INTO `models` (id, manu_id, name) VALUES ('118','12','Scout')
 INSERT INTO `models` (id, manu_id, name) VALUES ('119','13','Yo Electron ER')
 INSERT INTO `models` (id, manu_id, name) VALUES ('120','13','Yo EXL')
 INSERT INTO `models` (id, manu_id, name) VALUES ('121','13','Yo Explor')
 INSERT INTO `models` (id, manu_id, name) VALUES ('122','13','Yo Spark')
 INSERT INTO `models` (id, manu_id, name) VALUES ('123','14','ER-6n')
 INSERT INTO `models` (id, manu_id, name) VALUES ('124','14','Ninja')
 INSERT INTO `models` (id, manu_id, name) VALUES ('125','14','Versys')
 INSERT INTO `models` (id, manu_id, name) VALUES ('126','14','Z1000')
 INSERT INTO `models` (id, manu_id, name) VALUES ('127','14','Z250')
 INSERT INTO `models` (id, manu_id, name) VALUES ('128','14','Z800')
 INSERT INTO `models` (id, manu_id, name) VALUES ('129','14','ZX-6R')
 INSERT INTO `models` (id, manu_id, name) VALUES ('132','15','Adventure R')
 INSERT INTO `models` (id, manu_id, name) VALUES ('130','15','Duke')
 INSERT INTO `models` (id, manu_id, name) VALUES ('131','15','RC')
 INSERT INTO `models` (id, manu_id, name) VALUES ('133','16','E 1')
 INSERT INTO `models` (id, manu_id, name) VALUES ('134','17','2 Stroke')
 INSERT INTO `models` (id, manu_id, name) VALUES ('135','17','4 Stroke')
 INSERT INTO `models` (id, manu_id, name) VALUES ('136','17','Freedom')
 INSERT INTO `models` (id, manu_id, name) VALUES ('137','17','Star Euro')
 INSERT INTO `models` (id, manu_id, name) VALUES ('138','18','Frame')
 INSERT INTO `models` (id, manu_id, name) VALUES ('139','18','Genius')
 INSERT INTO `models` (id, manu_id, name) VALUES ('140','18','OMA Star')
 INSERT INTO `models` (id, manu_id, name) VALUES ('146','19','Arro')
 INSERT INTO `models` (id, manu_id, name) VALUES ('272','19','Bolero')
 INSERT INTO `models` (id, manu_id, name) VALUES ('141','19','Centure')
 INSERT INTO `models` (id, manu_id, name) VALUES ('142','19','Duro')
 INSERT INTO `models` (id, manu_id, name) VALUES ('273','19','e2o')
 INSERT INTO `models` (id, manu_id, name) VALUES ('143','19','Gusto')
 INSERT INTO `models` (id, manu_id, name) VALUES ('144','19','Mojo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('274','19','Quanto')
 INSERT INTO `models` (id, manu_id, name) VALUES ('145','19','Rodeo UZO')
 INSERT INTO `models` (id, manu_id, name) VALUES ('282','19','S101')
 INSERT INTO `models` (id, manu_id, name) VALUES ('275','19','Scorpio')
 INSERT INTO `models` (id, manu_id, name) VALUES ('276','19','Thar')
 INSERT INTO `models` (id, manu_id, name) VALUES ('277','19','TUV300')
 INSERT INTO `models` (id, manu_id, name) VALUES ('278','19','Verito')
 INSERT INTO `models` (id, manu_id, name) VALUES ('279','19','Verito Vibe')
 INSERT INTO `models` (id, manu_id, name) VALUES ('280','19','XUV500')
 INSERT INTO `models` (id, manu_id, name) VALUES ('281','19','Xylo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('147','20','California')
 INSERT INTO `models` (id, manu_id, name) VALUES ('148','20','Griso')
 INSERT INTO `models` (id, manu_id, name) VALUES ('149','20','Norge GT 8V')
 INSERT INTO `models` (id, manu_id, name) VALUES ('150','20','Stelvio')
 INSERT INTO `models` (id, manu_id, name) VALUES ('151','20','V7 ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('152','21','Brutale')
 INSERT INTO `models` (id, manu_id, name) VALUES ('153','21','F3')
 INSERT INTO `models` (id, manu_id, name) VALUES ('154','21','F4')
 INSERT INTO `models` (id, manu_id, name) VALUES ('155','21','RIVALE 800')
 INSERT INTO `models` (id, manu_id, name) VALUES ('156','21','Turismo Veloce')
 INSERT INTO `models` (id, manu_id, name) VALUES ('157','22','Outlaw')
 INSERT INTO `models` (id, manu_id, name) VALUES ('158','22','Ranger')
 INSERT INTO `models` (id, manu_id, name) VALUES ('159','22','RZR')
 INSERT INTO `models` (id, manu_id, name) VALUES ('160','22','Youth')
 INSERT INTO `models` (id, manu_id, name) VALUES ('161','23','Bobber')
 INSERT INTO `models` (id, manu_id, name) VALUES ('162','23','Cruiser')
 INSERT INTO `models` (id, manu_id, name) VALUES ('163','23','Daytona')
 INSERT INTO `models` (id, manu_id, name) VALUES ('165','24','Bullet Electra')
 INSERT INTO `models` (id, manu_id, name) VALUES ('170','24','Bullet Machismo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('164','24','Bullet Standard')
 INSERT INTO `models` (id, manu_id, name) VALUES ('166','24','Classic')
 INSERT INTO `models` (id, manu_id, name) VALUES ('167','24','Continental GT')
 INSERT INTO `models` (id, manu_id, name) VALUES ('169','24','Himalayan')
 INSERT INTO `models` (id, manu_id, name) VALUES ('168','24','Thunderbird')
 INSERT INTO `models` (id, manu_id, name) VALUES ('171','25','Access')
 INSERT INTO `models` (id, manu_id, name) VALUES ('172','25','Bandit')
 INSERT INTO `models` (id, manu_id, name) VALUES ('173','25','Gixxer')
 INSERT INTO `models` (id, manu_id, name) VALUES ('174','25','GSX')
 INSERT INTO `models` (id, manu_id, name) VALUES ('175','25','Hayabusa')
 INSERT INTO `models` (id, manu_id, name) VALUES ('176','25','Hayate')
 INSERT INTO `models` (id, manu_id, name) VALUES ('177','25','Intruder')
 INSERT INTO `models` (id, manu_id, name) VALUES ('178','25','Let\'s')
 INSERT INTO `models` (id, manu_id, name) VALUES ('179','25','Swish')
 INSERT INTO `models` (id, manu_id, name) VALUES ('180','25','V-Strom')
 INSERT INTO `models` (id, manu_id, name) VALUES ('181','27','Bonneville')
 INSERT INTO `models` (id, manu_id, name) VALUES ('182','27','Daytona 675')
 INSERT INTO `models` (id, manu_id, name) VALUES ('183','27','Rocket III Roadster')
 INSERT INTO `models` (id, manu_id, name) VALUES ('184','27','Speed Triple ABS')
 INSERT INTO `models` (id, manu_id, name) VALUES ('185','27','Street Triple ABS')
 INSERT INTO `models` (id, manu_id, name) VALUES ('186','27','Thruxton')
 INSERT INTO `models` (id, manu_id, name) VALUES ('187','27','Thunderbird')
 INSERT INTO `models` (id, manu_id, name) VALUES ('188','27','Tiger ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('189','28','Apache')
 INSERT INTO `models` (id, manu_id, name) VALUES ('198','28','Draken')
 INSERT INTO `models` (id, manu_id, name) VALUES ('190','28','Jupiter')
 INSERT INTO `models` (id, manu_id, name) VALUES ('191','28','Phoenix')
 INSERT INTO `models` (id, manu_id, name) VALUES ('192','28','Scooty Pep')
 INSERT INTO `models` (id, manu_id, name) VALUES ('193','28','Scooty Streak')
 INSERT INTO `models` (id, manu_id, name) VALUES ('194','28','Sport')
 INSERT INTO `models` (id, manu_id, name) VALUES ('195','28','Star City Plus')
 INSERT INTO `models` (id, manu_id, name) VALUES ('199','28','Victor')
 INSERT INTO `models` (id, manu_id, name) VALUES ('196','28','Wego')
 INSERT INTO `models` (id, manu_id, name) VALUES ('197','28','Zest')
 INSERT INTO `models` (id, manu_id, name) VALUES ('200','29','Elegante')
 INSERT INTO `models` (id, manu_id, name) VALUES ('203','29','FI')
 INSERT INTO `models` (id, manu_id, name) VALUES ('204','29','Liberty')
 INSERT INTO `models` (id, manu_id, name) VALUES ('201','29','SXL')
 INSERT INTO `models` (id, manu_id, name) VALUES ('202','29','VXL')
 INSERT INTO `models` (id, manu_id, name) VALUES ('205','31','Alpha')
 INSERT INTO `models` (id, manu_id, name) VALUES ('206','31','Crux')
 INSERT INTO `models` (id, manu_id, name) VALUES ('207','31','Fascino')
 INSERT INTO `models` (id, manu_id, name) VALUES ('208','31','Fazer')
 INSERT INTO `models` (id, manu_id, name) VALUES ('209','31','FZ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('210','31','FZ-S')
 INSERT INTO `models` (id, manu_id, name) VALUES ('211','31','FZ1')
 INSERT INTO `models` (id, manu_id, name) VALUES ('218','31','MT-03')
 INSERT INTO `models` (id, manu_id, name) VALUES ('219','31','MT25')
 INSERT INTO `models` (id, manu_id, name) VALUES ('212','31','Ray')
 INSERT INTO `models` (id, manu_id, name) VALUES ('213','31','Saluto')
 INSERT INTO `models` (id, manu_id, name) VALUES ('214','31','VMAX')
 INSERT INTO `models` (id, manu_id, name) VALUES ('215','31','YZF R1')
 INSERT INTO `models` (id, manu_id, name) VALUES ('216','31','YZF R15')
 INSERT INTO `models` (id, manu_id, name) VALUES ('217','31','YZF R3')
 INSERT INTO `models` (id, manu_id, name) VALUES ('220','31','YZF-R1S')
 INSERT INTO `models` (id, manu_id, name) VALUES ('221','31','YZF-R25')
 INSERT INTO `models` (id, manu_id, name) VALUES ('488','31','SZ-R')
 INSERT INTO `models` (id, manu_id, name) VALUES ('222','32','Alto')
 INSERT INTO `models` (id, manu_id, name) VALUES ('223','32','Baleno')
 INSERT INTO `models` (id, manu_id, name) VALUES ('224','32','Celerio')
 INSERT INTO `models` (id, manu_id, name) VALUES ('235','32','Cervo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('225','32','Ciaz')
 INSERT INTO `models` (id, manu_id, name) VALUES ('226','32','Eeco')
 INSERT INTO `models` (id, manu_id, name) VALUES ('227','32','Ertiga')
 INSERT INTO `models` (id, manu_id, name) VALUES ('228','32','Gypsy')
 INSERT INTO `models` (id, manu_id, name) VALUES ('236','32','Ignis')
 INSERT INTO `models` (id, manu_id, name) VALUES ('237','32','Jimny')
 INSERT INTO `models` (id, manu_id, name) VALUES ('238','32','MR Wagon')
 INSERT INTO `models` (id, manu_id, name) VALUES ('229','32','Omni')
 INSERT INTO `models` (id, manu_id, name) VALUES ('230','32','Ritz')
 INSERT INTO `models` (id, manu_id, name) VALUES ('231','32','S-Cross')
 INSERT INTO `models` (id, manu_id, name) VALUES ('232','32','Swift')
 INSERT INTO `models` (id, manu_id, name) VALUES ('233','32','Swift DZire')
 INSERT INTO `models` (id, manu_id, name) VALUES ('239','32','Vitara')
 INSERT INTO `models` (id, manu_id, name) VALUES ('234','32','Wagon R')
 INSERT INTO `models` (id, manu_id, name) VALUES ('240','32','XA Alpha')
 INSERT INTO `models` (id, manu_id, name) VALUES ('241','32','YBA Compact SUV')
 INSERT INTO `models` (id, manu_id, name) VALUES ('242','33','Verna')
 INSERT INTO `models` (id, manu_id, name) VALUES ('243','33','Creta')
 INSERT INTO `models` (id, manu_id, name) VALUES ('244','33','Elantra')
 INSERT INTO `models` (id, manu_id, name) VALUES ('245','33','Eon')
 INSERT INTO `models` (id, manu_id, name) VALUES ('246','33','i10')
 INSERT INTO `models` (id, manu_id, name) VALUES ('247','33','i20')
 INSERT INTO `models` (id, manu_id, name) VALUES ('248','33','Santa Fe')
 INSERT INTO `models` (id, manu_id, name) VALUES ('250','33','Tucson')
 INSERT INTO `models` (id, manu_id, name) VALUES ('249','33','Xcent')
 INSERT INTO `models` (id, manu_id, name) VALUES ('261','35','Camry')
 INSERT INTO `models` (id, manu_id, name) VALUES ('262','35','Corolla Altis')
 INSERT INTO `models` (id, manu_id, name) VALUES ('263','35','Etios')
 INSERT INTO `models` (id, manu_id, name) VALUES ('264','35','Etios Cross')
 INSERT INTO `models` (id, manu_id, name) VALUES ('265','35','Etios Liva')
 INSERT INTO `models` (id, manu_id, name) VALUES ('266','35','Fortuner')
 INSERT INTO `models` (id, manu_id, name) VALUES ('270','35','Hiace')
 INSERT INTO `models` (id, manu_id, name) VALUES ('267','35','Innova')
 INSERT INTO `models` (id, manu_id, name) VALUES ('268','35','Land Cruiser')
 INSERT INTO `models` (id, manu_id, name) VALUES ('269','35','Prius')
 INSERT INTO `models` (id, manu_id, name) VALUES ('271','35','Rush')
 INSERT INTO `models` (id, manu_id, name) VALUES ('283','37','Aria')
 INSERT INTO `models` (id, manu_id, name) VALUES ('284','37','Bolt')
 INSERT INTO `models` (id, manu_id, name) VALUES ('297','37','Hexa')
 INSERT INTO `models` (id, manu_id, name) VALUES ('285','37','Indica ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('286','37','Indigo ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('298','37','Kite Sedan')
 INSERT INTO `models` (id, manu_id, name) VALUES ('287','37','Manza')
 INSERT INTO `models` (id, manu_id, name) VALUES ('299','37','Manza CS')
 INSERT INTO `models` (id, manu_id, name) VALUES ('288','37','Movus')
 INSERT INTO `models` (id, manu_id, name) VALUES ('289','37','Nano ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('301','37','Q5 SUV')
 INSERT INTO `models` (id, manu_id, name) VALUES ('290','37','Safari')
 INSERT INTO `models` (id, manu_id, name) VALUES ('291','37','Sumo ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('292','37','Venture')
 INSERT INTO `models` (id, manu_id, name) VALUES ('293','37','Vista')
 INSERT INTO `models` (id, manu_id, name) VALUES ('294','37','Winger')
 INSERT INTO `models` (id, manu_id, name) VALUES ('295','37','Xenon XT')
 INSERT INTO `models` (id, manu_id, name) VALUES ('296','37','Zest')
 INSERT INTO `models` (id, manu_id, name) VALUES ('302','37','Zica')
 INSERT INTO `models` (id, manu_id, name) VALUES ('303','38','Classic')
 INSERT INTO `models` (id, manu_id, name) VALUES ('304','38','EcoSport')
 INSERT INTO `models` (id, manu_id, name) VALUES ('307','38','Endeavour')
 INSERT INTO `models` (id, manu_id, name) VALUES ('305','38','Fiesta')
 INSERT INTO `models` (id, manu_id, name) VALUES ('306','38','Figo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('308','38','Kuga')
 INSERT INTO `models` (id, manu_id, name) VALUES ('309','38','Mondeo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('310','38','Mustang')
 INSERT INTO `models` (id, manu_id, name) VALUES ('311','39','Beat')
 INSERT INTO `models` (id, manu_id, name) VALUES ('320','39','Beat Electric')
 INSERT INTO `models` (id, manu_id, name) VALUES ('312','39','Captiva')
 INSERT INTO `models` (id, manu_id, name) VALUES ('313','39','Cruze')
 INSERT INTO `models` (id, manu_id, name) VALUES ('314','39','Enjoy')
 INSERT INTO `models` (id, manu_id, name) VALUES ('321','39','Orlando')
 INSERT INTO `models` (id, manu_id, name) VALUES ('315','39','Sail')
 INSERT INTO `models` (id, manu_id, name) VALUES ('316','39','Sail Hatchback')
 INSERT INTO `models` (id, manu_id, name) VALUES ('317','39','Spark')
 INSERT INTO `models` (id, manu_id, name) VALUES ('322','39','Spin')
 INSERT INTO `models` (id, manu_id, name) VALUES ('318','39','Tavera')
 INSERT INTO `models` (id, manu_id, name) VALUES ('319','39','Trailblazer')
 INSERT INTO `models` (id, manu_id, name) VALUES ('323','39','Trax')
 INSERT INTO `models` (id, manu_id, name) VALUES ('330','40','Clio')
 INSERT INTO `models` (id, manu_id, name) VALUES ('331','40','Dokker')
 INSERT INTO `models` (id, manu_id, name) VALUES ('332','40','Duster')
 INSERT INTO `models` (id, manu_id, name) VALUES ('324','40','Fluence')
 INSERT INTO `models` (id, manu_id, name) VALUES ('325','40','Koleos')
 INSERT INTO `models` (id, manu_id, name) VALUES ('326','40','KWID')
 INSERT INTO `models` (id, manu_id, name) VALUES ('333','40','Laguna')
 INSERT INTO `models` (id, manu_id, name) VALUES ('327','40','Lodgy')
 INSERT INTO `models` (id, manu_id, name) VALUES ('334','40','Modus')
 INSERT INTO `models` (id, manu_id, name) VALUES ('328','40','Pulse')
 INSERT INTO `models` (id, manu_id, name) VALUES ('329','40','Scala')
 INSERT INTO `models` (id, manu_id, name) VALUES ('335','40','Scenic')
 INSERT INTO `models` (id, manu_id, name) VALUES ('336','40','Talisman')
 INSERT INTO `models` (id, manu_id, name) VALUES ('337','40','XBA')
 INSERT INTO `models` (id, manu_id, name) VALUES ('341','41','Beetle')
 INSERT INTO `models` (id, manu_id, name) VALUES ('342','41','Golf')
 INSERT INTO `models` (id, manu_id, name) VALUES ('338','41','Jetta')
 INSERT INTO `models` (id, manu_id, name) VALUES ('343','41','Passat')
 INSERT INTO `models` (id, manu_id, name) VALUES ('339','41','Polo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('344','41','T-Roc')
 INSERT INTO `models` (id, manu_id, name) VALUES ('345','41','Taigun')
 INSERT INTO `models` (id, manu_id, name) VALUES ('346','41','Tiguan')
 INSERT INTO `models` (id, manu_id, name) VALUES ('347','41','Up')
 INSERT INTO `models` (id, manu_id, name) VALUES ('340','41','Vento')
 INSERT INTO `models` (id, manu_id, name) VALUES ('348','42','DB9')
 INSERT INTO `models` (id, manu_id, name) VALUES ('349','42','Rapide S')
 INSERT INTO `models` (id, manu_id, name) VALUES ('350','42','V12 Vantage')
 INSERT INTO `models` (id, manu_id, name) VALUES ('351','42','Vanquish')
 INSERT INTO `models` (id, manu_id, name) VALUES ('365','43','A1')
 INSERT INTO `models` (id, manu_id, name) VALUES ('352','43','A3')
 INSERT INTO `models` (id, manu_id, name) VALUES ('353','43','A4')
 INSERT INTO `models` (id, manu_id, name) VALUES ('366','43','A5')
 INSERT INTO `models` (id, manu_id, name) VALUES ('354','43','A6')
 INSERT INTO `models` (id, manu_id, name) VALUES ('355','43','A8L')
 INSERT INTO `models` (id, manu_id, name) VALUES ('356','43','Q3')
 INSERT INTO `models` (id, manu_id, name) VALUES ('357','43','Q5')
 INSERT INTO `models` (id, manu_id, name) VALUES ('358','43','Q7')
 INSERT INTO `models` (id, manu_id, name) VALUES ('359','43','R8')
 INSERT INTO `models` (id, manu_id, name) VALUES ('360','43','RS5')
 INSERT INTO `models` (id, manu_id, name) VALUES ('361','43','RS6')
 INSERT INTO `models` (id, manu_id, name) VALUES ('362','43','RS7 ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('363','43','S5')
 INSERT INTO `models` (id, manu_id, name) VALUES ('364','43','TT')
 INSERT INTO `models` (id, manu_id, name) VALUES ('371','45','Bentayga')
 INSERT INTO `models` (id, manu_id, name) VALUES ('367','45','Continental Flying Spur')
 INSERT INTO `models` (id, manu_id, name) VALUES ('368','45','Continental GT')
 INSERT INTO `models` (id, manu_id, name) VALUES ('369','45','Continental GTC')
 INSERT INTO `models` (id, manu_id, name) VALUES ('370','45','Mulsanne')
 INSERT INTO `models` (id, manu_id, name) VALUES ('388','47','Chiron')
 INSERT INTO `models` (id, manu_id, name) VALUES ('389','48','Go')
 INSERT INTO `models` (id, manu_id, name) VALUES ('390','49','Avanti')
 INSERT INTO `models` (id, manu_id, name) VALUES ('391','50','458 Speciale')
 INSERT INTO `models` (id, manu_id, name) VALUES ('392','50','458 Spider')
 INSERT INTO `models` (id, manu_id, name) VALUES ('393','50','488 GTB')
 INSERT INTO `models` (id, manu_id, name) VALUES ('394','50','California T')
 INSERT INTO `models` (id, manu_id, name) VALUES ('395','50','F12 Berlinetta')
 INSERT INTO `models` (id, manu_id, name) VALUES ('396','50','F620 GT')
 INSERT INTO `models` (id, manu_id, name) VALUES ('397','51','Abarth 595')
 INSERT INTO `models` (id, manu_id, name) VALUES ('398','51','Abarth Avventura')
 INSERT INTO `models` (id, manu_id, name) VALUES ('399','51','Abarth Punto')
 INSERT INTO `models` (id, manu_id, name) VALUES ('400','51','Avventura')
 INSERT INTO `models` (id, manu_id, name) VALUES ('401','51','Linea')
 INSERT INTO `models` (id, manu_id, name) VALUES ('403','51','Panda')
 INSERT INTO `models` (id, manu_id, name) VALUES ('402','51','Punto Evo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('404','51','Tipo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('405','51','Viaggio')
 INSERT INTO `models` (id, manu_id, name) VALUES ('406','52','Gurkha')
 INSERT INTO `models` (id, manu_id, name) VALUES ('407','52','One')
 INSERT INTO `models` (id, manu_id, name) VALUES ('408','53','Extreme')
 INSERT INTO `models` (id, manu_id, name) VALUES ('411','55','C-X17')
 INSERT INTO `models` (id, manu_id, name) VALUES ('412','55','F-Pace')
 INSERT INTO `models` (id, manu_id, name) VALUES ('409','55','F-Type')
 INSERT INTO `models` (id, manu_id, name) VALUES ('413','55','XE')
 INSERT INTO `models` (id, manu_id, name) VALUES ('410','55','XF')
 INSERT INTO `models` (id, manu_id, name) VALUES ('414','55','XJ')
 INSERT INTO `models` (id, manu_id, name) VALUES ('415','56','Grand Cherokee')
 INSERT INTO `models` (id, manu_id, name) VALUES ('416','56','Wrangler')
 INSERT INTO `models` (id, manu_id, name) VALUES ('417','57','Aventador')
 INSERT INTO `models` (id, manu_id, name) VALUES ('418','57','Huracan')
 INSERT INTO `models` (id, manu_id, name) VALUES ('419','58','Discovery Sport')
 INSERT INTO `models` (id, manu_id, name) VALUES ('420','58','Freelander 2')
 INSERT INTO `models` (id, manu_id, name) VALUES ('421','58','Range Rover')
 INSERT INTO `models` (id, manu_id, name) VALUES ('423','59','Korando')
 INSERT INTO `models` (id, manu_id, name) VALUES ('422','59','Rexton')
 INSERT INTO `models` (id, manu_id, name) VALUES ('424','59','Tivoli')
 INSERT INTO `models` (id, manu_id, name) VALUES ('425','60','Ghibli')
 INSERT INTO `models` (id, manu_id, name) VALUES ('426','60','GranCabrio')
 INSERT INTO `models` (id, manu_id, name) VALUES ('427','60','GranTurismo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('428','60','Quattroporte')
 INSERT INTO `models` (id, manu_id, name) VALUES ('429','61','A-Class')
 INSERT INTO `models` (id, manu_id, name) VALUES ('430','61','AMG-GT')
 INSERT INTO `models` (id, manu_id, name) VALUES ('431','61','B-class')
 INSERT INTO `models` (id, manu_id, name) VALUES ('432','61','C-Class')
 INSERT INTO `models` (id, manu_id, name) VALUES ('433','61','CLA-Class')
 INSERT INTO `models` (id, manu_id, name) VALUES ('434','61','CLS')
 INSERT INTO `models` (id, manu_id, name) VALUES ('435','61','E-Class')
 INSERT INTO `models` (id, manu_id, name) VALUES ('436','61','G-Class')
 INSERT INTO `models` (id, manu_id, name) VALUES ('437','61','GL')
 INSERT INTO `models` (id, manu_id, name) VALUES ('438','61','GLA Class')
 INSERT INTO `models` (id, manu_id, name) VALUES ('443','61','GLC')
 INSERT INTO `models` (id, manu_id, name) VALUES ('439','61','GLE-Class')
 INSERT INTO `models` (id, manu_id, name) VALUES ('444','61','GLS')
 INSERT INTO `models` (id, manu_id, name) VALUES ('440','61','Maybach')
 INSERT INTO `models` (id, manu_id, name) VALUES ('441','61','S-Class')
 INSERT INTO `models` (id, manu_id, name) VALUES ('442','61','SLK-Class')
 INSERT INTO `models` (id, manu_id, name) VALUES ('448','62','Clubman')
 INSERT INTO `models` (id, manu_id, name) VALUES ('445','62','Convertible')
 INSERT INTO `models` (id, manu_id, name) VALUES ('446','62','Cooper')
 INSERT INTO `models` (id, manu_id, name) VALUES ('447','62','Countryman')
 INSERT INTO `models` (id, manu_id, name) VALUES ('450','63','EVO XI')
 INSERT INTO `models` (id, manu_id, name) VALUES ('451','63','Grandis')
 INSERT INTO `models` (id, manu_id, name) VALUES ('452','63','Mirage')
 INSERT INTO `models` (id, manu_id, name) VALUES ('449','63','Pajero')
 INSERT INTO `models` (id, manu_id, name) VALUES ('454','64','Evalia')
 INSERT INTO `models` (id, manu_id, name) VALUES ('458','64','GTR')
 INSERT INTO `models` (id, manu_id, name) VALUES ('459','64','Kicks')
 INSERT INTO `models` (id, manu_id, name) VALUES ('455','64','Micra')
 INSERT INTO `models` (id, manu_id, name) VALUES ('460','64','Patrol')
 INSERT INTO `models` (id, manu_id, name) VALUES ('461','64','Qashqai')
 INSERT INTO `models` (id, manu_id, name) VALUES ('456','64','Sunny')
 INSERT INTO `models` (id, manu_id, name) VALUES ('457','64','Terrano')
 INSERT INTO `models` (id, manu_id, name) VALUES ('462','64','X-Trail')
 INSERT INTO `models` (id, manu_id, name) VALUES ('463','65','911')
 INSERT INTO `models` (id, manu_id, name) VALUES ('464','65','Boxster')
 INSERT INTO `models` (id, manu_id, name) VALUES ('465','65','Cayenne')
 INSERT INTO `models` (id, manu_id, name) VALUES ('466','65','Cayman')
 INSERT INTO `models` (id, manu_id, name) VALUES ('467','65','Macan')
 INSERT INTO `models` (id, manu_id, name) VALUES ('468','65','Panamera')
 INSERT INTO `models` (id, manu_id, name) VALUES ('473','67','Dawn')
 INSERT INTO `models` (id, manu_id, name) VALUES ('469','67','Drophead Coupe')
 INSERT INTO `models` (id, manu_id, name) VALUES ('470','67','Ghost')
 INSERT INTO `models` (id, manu_id, name) VALUES ('471','67','Phantom')
 INSERT INTO `models` (id, manu_id, name) VALUES ('472','67','Wraith')
 INSERT INTO `models` (id, manu_id, name) VALUES ('478','68','Citigo')
 INSERT INTO `models` (id, manu_id, name) VALUES ('474','68','Octavia')
 INSERT INTO `models` (id, manu_id, name) VALUES ('475','68','Rapid')
 INSERT INTO `models` (id, manu_id, name) VALUES ('476','68','Superb')
 INSERT INTO `models` (id, manu_id, name) VALUES ('477','68','Yeti')
 INSERT INTO `models` (id, manu_id, name) VALUES ('484','69','C70')
 INSERT INTO `models` (id, manu_id, name) VALUES ('479','69','S60')
 INSERT INTO `models` (id, manu_id, name) VALUES ('480','69','S80')
 INSERT INTO `models` (id, manu_id, name) VALUES ('485','69','S90')
 INSERT INTO `models` (id, manu_id, name) VALUES ('481','69','V40')
 INSERT INTO `models` (id, manu_id, name) VALUES ('486','69','XC30')
 INSERT INTO `models` (id, manu_id, name) VALUES ('487','69','XC40')
 INSERT INTO `models` (id, manu_id, name) VALUES ('482','69','XC60')
 INSERT INTO `models` (id, manu_id, name) VALUES ('483','69','XC90')

